@host = http://localhost:3000

GET {{host}}/clinicas-submetidas
###

GET {{host}}/users 
###
POST {{host}}/users
Content-Type: application/json

{
    "username": "carlos",
    "email": "carlos@gmail.com",
    "password": "12345678",
   "confirmationPassword": "12345678"
}
###

POST {{host}}/signin
Content-Type: application/json

{
    "email": "calos@gmail.com",
    "password": "12345678"
}
###

POST {{host}}/clinicas-submetidas
Content-Type: application/json

{
    "name": "teste",
    "img": "imgteste"
}

### Create Image

POST {{host}}/users/image
Authorization: bearer {{token}}
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="userId"

{{createdUserId}}
--boundary
Content-Disposition: form-data; name="image"; filename="avatar.png"
Content-Type: image/png

< ./public/imgs/profile/avatar.png
--boundary--
