@host = http://localhost:3000

GET {{host}}/clinicas-submetidas


GET {{host}}/users 

POST {{host}}/users
Content-Type: application/json

{
    "username": "imteste",
    "email": "imteste@email.com",
    "password": "imteste123"
}


POST {{host}}/signin
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "teste12345678"
}