@host = http://localhost:3000

GET {{host}}/clinicas-submetidas


GET {{host}}/users 

POST {{host}}/users
Content-Type: application/json

{
    "username": "teste",
    "email": "teste@email.com",
    "password": "teste123"
}

POST {{host}}/signin
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "teste123"
}
